name: Bug Report
description: "File a new bug report"
title: "[Bug]: "
labels: ["🐛 Bug", "🔍 Triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important
        - Ensure you are using the latest version of Coolify before reporting a bug.
        - Consider adding a bounty to prioritize this issue through our [Bounty Program](https://console.algora.io/org/coollabsio/bounties/new).

  - type: textarea
    id: error-and-logs
    attributes:
      label: Error Message and Logs
      description: Provide a detailed description of the error or exception you encountered, along with any relevant log output
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue (please do this in detail otherwise we will not be able to help you)
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: input
    id: example-repo
    attributes:
      label: Example Repository URL
      description: If applicable, provide a URL to a repository demonstrating the issue

  - type: input
    id: coolify-version
    attributes:
      label: Coolify Version
      description: Found in the top left corner of your Coolify dashboard
      placeholder: "e.g., v4.0.0-beta.335"
    validations:
      required: true

  - type: dropdown
    id: cloud-version
    attributes:
      label: Are you using Coolify Cloud?
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: Run `cat /etc/os-release` or `lsb_release -a` in your terminal
      placeholder: "e.g., Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant details about the issue
