name: 🐞 Bug Report
description: "File a new bug report"
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        # 💎 Bounty Program (with [algora.io](https://console.algora.io/org/coollabsio/bounties/new))
        - If you would like to prioritize the issue resolution, consider adding a bounty to this issue through our [Bounty Program](https://console.algora.io/org/coollabsio/bounties/new).

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue. Please be as detailed as possible, otherwise we may not be able to assist you.
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Exception or Error
      description: Please provide error logs if possible.
  - type: input
    attributes:
      label: Coolify Version
      description: Please provide the Coolify version you are using. This can be found in the top left corner of your Coolify dashboard.
      placeholder: "v4.0.0-beta.335"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System and Version (self-hosted)
      description: Run `cat /etc/os-release` or `lsb_release -a` in your terminal and provide the operating system and version.
      placeholder: "Ubuntu 22.04"

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant details about the issue.

  - type: checkboxes
    id: using-latest-version
    attributes:
      label: Make sure you are using the latest version of Coolify before submitting this issue.
      options:
        - label: I confirm that I am using the latest version of Coolify.
          required: true
