name: Close Stale Issues and PRs

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 1 * * *'  # Run daily at 1 AM UTC

jobs:
  close-stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is being closed due to inactivity. Please reopen if you need further assistance.'
          stale-pr-message: 'This pull request is being closed due to inactivity. Please reopen if you would like to continue working on it.'
          close-issue-message: 'This issue has been closed due to inactivity.'
          close-pr-message: 'This pull request has been closed due to inactivity.'
          days-before-stale: 0
          days-before-close: 0
          stale-issue-label: '⏱︎ Stale'
          stale-pr-label: '⏱︎ Stale'
          only-labels: '💤 Waiting for feedback'
          operations-per-run: 100
